In [1]:
words = open('/content/text.txt', 'r').read().split()
words[:20]

['So',
 'Ray',
 'J',
 'went',
 'straight',
 'to',
 'the',
 'radio',
 'station',
 'The',
 'very',
 'next',
 'day,',
 '"Hey',
 'Fab,',
 "I'ma",
 'kill',
 'you!"',
 'Lyrics',
 "comin'"]

In [2]:
#from karpathy
# create a bigram by sliding across 2 words at a time
data = {}
for w in words:
  chars = list(w)
  for ch1, ch2 in zip(chars, chars[2:]):
    bigram = (ch1, ch2)
    data[bigram] = data.get(bigram, 0) + 1



In [3]:
sorted(data.items(), key = lambda kv: -kv[1])

[(('t', 'e'), 11),
 (('a', 'i'), 9),
 (('i', 'g'), 9),
 (('t', 'a'), 7),
 (('i', "'"), 7),
 (('h', 't'), 7),
 (('a', 'e'), 7),
 (('t', 'n'), 7),
 (('y', 'u'), 6),
 (('u', 'e'), 6),
 (('a', 'd'), 6),
 (('e', 'e'), 6),
 (('g', 't'), 5),
 (('I', 'm'), 5),
 (('m', 'n'), 5),
 (('v', 't'), 5),
 (('e', 'l'), 5),
 (('h', 'y'), 5),
 (('v', 'r'), 4),
 (('u', 'i'), 4),
 (('n', 't'), 4),
 (('o', 'e'), 4),
 (('t', 's'), 4),
 (('s', 'r'), 3),
 (('i', 'h'), 3),
 (('t', 't'), 3),
 (("'", 'a'), 3),
 (('r', 'c'), 3),
 (('o', 'i'), 3),
 (('e', 's'), 3),
 (('u', 'm'), 3),
 (('m', 'a'), 3),
 (('m', ','), 3),
 (('a', 's'), 3),
 (('t', 'r'), 3),
 (('r', 'u'), 3),
 (('i', 'e'), 3),
 (('h', 'n'), 3),
 (('e', 'i'), 3),
 (('o', 'f'), 3),
 (('e', 'a'), 3),
 (('l', 'v'), 3),
 (('m', 'k'), 3),
 (('e', 't'), 2),
 (('d', 'o'), 2),
 (('s', 'a'), 2),
 (('t', 'o'), 2),
 (('i', 'n'), 2),
 (('d', 'y'), 2),
 (('a', ','), 2),
 (('i', 's'), 2),
 (('s', 'p'), 2),
 (('p', 'r'), 2),
 (('s', 'm'), 2),
 (('m', '-'), 2),
 (('a', '

In [4]:
char = sorted(list(set(words)))

In [9]:
# split the training data

string2integer = {ch: i for i, ch in enumerate(chars)}
print(string2integer)

integer2string = {i:ch for ch,i in string2integer.items()}
encode = lambda s: [string2integer[c] for c in s]
print(encode)

decode = lambda l: ''.join([integer2string[i] for i in l])
print(decode)

data = torch.tensor(encode(words), dtype = torch.long)
print(data)

{'"': 0, '"Hey': 1, '"It\'s': 2, '"Lose': 3, '"Oh,': 4, "'Cause": 5, "'cause": 6, "'em": 7, '(J.J.': 8, 'Doc': 9, 'Fab,': 10, 'Fad)': 11, 'For': 12, 'How': 13, 'I': 14, "I'm": 15, "I'ma": 16, 'Innovative': 17, 'J': 18, 'Lyrics': 19, 'Never': 20, 'Ray': 21, 'So': 22, 'The': 23, 'Throw': 24, 'Uh,': 25, 'Well,': 26, 'What': 27, 'With': 28, 'You': 29, 'Yourself"': 30, 'a': 31, 'and': 32, 'anything': 33, 'are': 34, "assumin'": 35, 'at': 36, 'audience': 37, 'be': 38, 'can': 39, 'celebrating': 40, "comin'": 41, 'confuse': 42, 'day': 43, 'day,': 44, 'demonstrating': 45, 'devastating,': 46, 'do': 47, 'dooma-lumma,': 48, 'elevating': 49, 'elevator': 50, 'ever': 51, 'fading,': 52, 'feeling': 53, 'fell': 54, 'forever': 55, 'found': 56, 'fuse': 57, 'get': 58, 'give': 59, 'glue': 60, 'gotta': 61, 'haters': 62, "he's": 63, 'hella': 64, 'hip-hop,': 65, 'human': 66, 'is': 67, 'it': 68, "it'll": 69, "it's": 70, 'jealous,': 71, 'kill': 72, 'know': 73, 'levitating': 74, 'like': 75, 'lose': 76, 'made': 77,

In [51]:
import torch

n = int(0.4 * len(words))
train_data = data[:n]
val_data = data[n:]
print(val_data)

p = decode(val_data[:18].tolist())
p

tensor([ 32,  15,  46,  81, 107,  51,  45,  13, 114,  59,  31,  82,  37,  31,
         53,  75,  70,  74,  20,  52,  32,  14,  73, 110,  62,  34,  55, 117,
         12, 110,  43, 108, 111,  39,  98,  14,  54,  90, 112,  38,  40,   5,
         14,  73, 110, 118, 114,  58,   7,  83,  14,  79,  49,  85, 123,  79,
         50,  84,   4,  63, 115,  78,  26, 109, 120, 111,  47, 121, 111,  58,
         71, 111,  42,  68,   2,  87,  65,  70,  92,   0,   6,  14,  56,  31,
         64, 118, 114,  57,  68,  28,  96,  99,  94, 122,   9,  24,  91,   3,
         30,  32,  79,   7,  76,  68])


"andI'mdevastating,morethaneverdemonstratingHowtogiveamotherfuckin'audienceafeelinglikeit'slevitating"

In [11]:
string2integer = {ch: i for i, ch in enumerate(char)}
print(string2integer)

res = dict(enumerate(words))
print(res)
keyList = [key for key in res]
print(keyList)
l = len(keyList)
l


{'"': 0, '"Hey': 1, '"It\'s': 2, '"Lose': 3, '"Oh,': 4, "'Cause": 5, "'cause": 6, "'em": 7, '(J.J.': 8, 'Doc': 9, 'Fab,': 10, 'Fad)': 11, 'For': 12, 'How': 13, 'I': 14, "I'm": 15, "I'ma": 16, 'Innovative': 17, 'J': 18, 'Lyrics': 19, 'Never': 20, 'Ray': 21, 'So': 22, 'The': 23, 'Throw': 24, 'Uh,': 25, 'Well,': 26, 'What': 27, 'With': 28, 'You': 29, 'Yourself"': 30, 'a': 31, 'and': 32, 'anything': 33, 'are': 34, "assumin'": 35, 'at': 36, 'audience': 37, 'be': 38, 'can': 39, 'celebrating': 40, "comin'": 41, 'confuse': 42, 'day': 43, 'day,': 44, 'demonstrating': 45, 'devastating,': 46, 'do': 47, 'dooma-lumma,': 48, 'elevating': 49, 'elevator': 50, 'ever': 51, 'fading,': 52, 'feeling': 53, 'fell': 54, 'forever': 55, 'found': 56, 'fuse': 57, 'get': 58, 'give': 59, 'glue': 60, 'gotta': 61, 'haters': 62, "he's": 63, 'hella': 64, 'hip-hop,': 65, 'human': 66, 'is': 67, 'it': 68, "it'll": 69, "it's": 70, 'jealous,': 71, 'kill': 72, 'know': 73, 'levitating': 74, 'like': 75, 'lose': 76, 'made': 77,

172

In [12]:
# scaled dot product attention
# 3 matrices, Q -> query matrix
# K -> Key matrix
# V -> value matrix
# T is the length of the sequence
import math
import numpy as np 
import torch.nn.functional  as F
import torch

def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size()[-1]
    attn_logits = torch.matmul(q, k.transpose(-2, -1))
    attn_logits = attn_logits / math.sqrt(d_k)
    if mask is not None:
        attn_logits = attn_logits.masked_fill(mask == 0, -9e15)
    attention = F.softmax(attn_logits, dim=-1)
    values = torch.matmul(attention, v)
    return values, attention

Dk and Dv
 are the hidden dimensionality for queries/keys and values respectively

In [47]:

import torch
chars = sorted(list(set(words)))
# print(chars)
size = len(chars) # sequence length
# print(size)


d_k = 2

torch.manual_seed(1337)

q = torch.randn(size, d_k)

#q = torch.randn(size, d_k).detach().requires_grad_(True)


k = torch.randn(size, d_k)
v = torch.randn(size, d_k)
values, attention = scaled_dot_product(q, k, v)
# print("Q\n", q)
# print("K\n", k)
# print("V\n", v)
print("Values\n", values[:5].reshape(1, -1))
print("Attention\n", attention[:5].reshape(1, -1))
# p = torch.Tensor(values)
# p

values.tolist()


Values
 tensor([[-0.0024,  0.0350, -0.0502,  0.0396,  0.0462,  0.0850,  0.0854,  0.1279,
          0.0942,  0.0176]])
Attention
 tensor([[0.0082, 0.0072, 0.0058, 0.0073, 0.0079, 0.0100, 0.0100, 0.0078, 0.0066,
         0.0067, 0.0076, 0.0076, 0.0064, 0.0107, 0.0067, 0.0085, 0.0071, 0.0081,
         0.0073, 0.0090, 0.0070, 0.0065, 0.0071, 0.0062, 0.0083, 0.0093, 0.0084,
         0.0106, 0.0094, 0.0092, 0.0097, 0.0066, 0.0079, 0.0071, 0.0103, 0.0086,
         0.0114, 0.0071, 0.0067, 0.0075, 0.0074, 0.0101, 0.0089, 0.0077, 0.0071,
         0.0078, 0.0079, 0.0074, 0.0084, 0.0079, 0.0067, 0.0083, 0.0083, 0.0068,
         0.0084, 0.0078, 0.0060, 0.0077, 0.0079, 0.0081, 0.0072, 0.0071, 0.0091,
         0.0077, 0.0090, 0.0085, 0.0091, 0.0080, 0.0077, 0.0074, 0.0088, 0.0093,
         0.0098, 0.0063, 0.0087, 0.0078, 0.0071, 0.0080, 0.0076, 0.0093, 0.0088,
         0.0073, 0.0080, 0.0063, 0.0082, 0.0078, 0.0072, 0.0103, 0.0080, 0.0086,
         0.0073, 0.0081, 0.0085, 0.0071, 0.0075, 0.0063, 0.00

[[-0.0024424297735095024, 0.03498305007815361],
 [-0.0501624196767807, 0.03959700092673302],
 [0.04617688059806824, 0.08497251570224762],
 [0.08537837117910385, 0.12790809571743011],
 [0.09422030299901962, 0.017580706626176834],
 [-0.1264338195323944, 0.023994464427232742],
 [0.0025613093748688698, 0.04516937583684921],
 [-0.06211200729012489, -0.14241114258766174],
 [0.11488746851682663, 0.1844596415758133],
 [0.05125867575407028, 0.019085992127656937],
 [-0.08051830530166626, -0.12789437174797058],
 [0.20601417124271393, 0.18496569991111755],
 [0.01212971843779087, 0.07835806906223297],
 [-0.10039400309324265, -0.010585237294435501],
 [0.02608320116996765, 0.07921285182237625],
 [1.2068867683410645, -0.21861863136291504],
 [-0.06788432598114014, -0.01689816452562809],
 [0.09440574795007706, 0.13482502102851868],
 [0.04743099957704544, -0.001893987413495779],
 [-0.09803761541843414, -0.015557566657662392],
 [-0.06463038921356201, 0.03987928479909897],
 [0.044606633484363556, 0.1008201

In [ ]:
# b = sorted(list(set(values[:n])))

# d  = torch.stack(b)
# d
# g = sorted(list(set(attention[:5])))


###  Tensor ops to be continued

In [ ]:
N = torch.zeros((40, 40), dtype=torch.int32)


### Demystifying queries Keys and Values

In [ ]:
words = open('/content/text.txt', 'r').read().split()
words[:20]

In [14]:
import torch
from torch import nn

chars = sorted(list(set(words)))
string2integer = {ch: i for i, ch in enumerate(chars)}
print(string2integer)

integer2string = {i:ch for ch,i in string2integer.items()}
encode = lambda s: [string2integer[c] for c in s]
print(encode)

decode = lambda l: ''.join([integer2string[i] for i in l])
print(decode)

data = torch.tensor(encode(words), dtype = torch.long)
print(data)

{'"': 0, '"Hey': 1, '"It\'s': 2, '"Lose': 3, '"Oh,': 4, "'Cause": 5, "'cause": 6, "'em": 7, '(J.J.': 8, 'Doc': 9, 'Fab,': 10, 'Fad)': 11, 'For': 12, 'How': 13, 'I': 14, "I'm": 15, "I'ma": 16, 'Innovative': 17, 'J': 18, 'Lyrics': 19, 'Never': 20, 'Ray': 21, 'So': 22, 'The': 23, 'Throw': 24, 'Uh,': 25, 'Well,': 26, 'What': 27, 'With': 28, 'You': 29, 'Yourself"': 30, 'a': 31, 'and': 32, 'anything': 33, 'are': 34, "assumin'": 35, 'at': 36, 'audience': 37, 'be': 38, 'can': 39, 'celebrating': 40, "comin'": 41, 'confuse': 42, 'day': 43, 'day,': 44, 'demonstrating': 45, 'devastating,': 46, 'do': 47, 'dooma-lumma,': 48, 'elevating': 49, 'elevator': 50, 'ever': 51, 'fading,': 52, 'feeling': 53, 'fell': 54, 'forever': 55, 'found': 56, 'fuse': 57, 'get': 58, 'give': 59, 'glue': 60, 'gotta': 61, 'haters': 62, "he's": 63, 'hella': 64, 'hip-hop,': 65, 'human': 66, 'is': 67, 'it': 68, "it'll": 69, "it's": 70, 'jealous,': 71, 'kill': 72, 'know': 73, 'levitating': 74, 'like': 75, 'lose': 76, 'made': 77,

In [28]:
vocab_size = len(chars)

d_k = 2

token_emb = nn.Embedding(vocab_size, d_k)
token_emb

Embedding(125, 2)

In [29]:
input_embeddings = token_emb(data)
input_embeddings.size()

torch.Size([172, 2])

#### Now, create the query, key and value vectors and calculate the attention scores based on the dot product as the similarity function

In [31]:
import torch
from math import sqrt 

query = key = value = input_embeddings
dim_k = key.size(-1)
print(dim_k)
scores = torch.matmul(query, key.transpose(1,-2))/sqrt(dim_k)
print(scores)
scores.size()

2
tensor([[ 1.0342,  0.2054, -1.5626,  ...,  0.1081,  0.5004,  1.1613],
        [ 0.2054,  0.7806,  0.4476,  ...,  0.7237, -0.3282,  0.4966],
        [-1.5626,  0.4476,  3.1375,  ...,  0.5561, -1.1942, -1.4822],
        ...,
        [ 0.1081,  0.7237,  0.5561,  ...,  0.6778, -0.3536,  0.3737],
        [ 0.5004, -0.3282, -1.1942,  ..., -0.3536,  0.4893,  0.4082],
        [ 1.1613,  0.4966, -1.4822,  ...,  0.3737,  0.4082,  1.3996]],
       grad_fn=<DivBackward0>)


torch.Size([172, 172])

##### Now, lets apply the softmax function

In [34]:
import torch.nn.functional as F
weights = F.softmax(scores, dim = -1)
weights.sum(dim = -1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 

In [37]:
attention_logits = torch.matmul(weights, value)
attention_logits.shape
### Now look at the scaled dot product function above

torch.Size([172, 2])

In [53]:
#m = decode(scores[:3].tolist())
m = scores[:5].tolist()
m[:1]

[[1.0342422723770142,
  0.20540887117385864,
  -1.5626333951950073,
  -0.05896643549203873,
  -0.9931272268295288,
  -0.47809404134750366,
  -0.18479514122009277,
  0.801186203956604,
  -1.481999397277832,
  -0.6528627872467041,
  0.6440685391426086,
  -0.6117128729820251,
  2.2193775177001953,
  -0.6889744400978088,
  0.1810396909713745,
  1.1753352880477905,
  -1.5324331521987915,
  0.027971414849162102,
  0.9061397314071655,
  0.7818080186843872,
  -0.3954094350337982,
  0.8335515260696411,
  -0.3954094350337982,
  0.8242469429969788,
  -0.7864075303077698,
  0.5478734970092773,
  -0.36804521083831787,
  -1.5315810441970825,
  -0.6273103356361389,
  -0.7414959073066711,
  0.8335515260696411,
  -0.43255582451820374,
  -0.5283082723617554,
  0.18301750719547272,
  -1.1334327459335327,
  -0.6214486956596375,
  0.7942524552345276,
  0.14834068715572357,
  0.054729580879211426,
  -0.47809404134750366,
  0.17520080506801605,
  1.161338448524475,
  1.0053986310958862,
  -0.4780940413475036