In [1]:
words = open('/content/text.txt', 'r').read().split()
words[:20]

['So',
 'Ray',
 'J',
 'went',
 'straight',
 'to',
 'the',
 'radio',
 'station',
 'The',
 'very',
 'next',
 'day,',
 '"Hey',
 'Fab,',
 "I'ma",
 'kill',
 'you!"',
 'Lyrics',
 "comin'"]

In [2]:
#from karpathy
# create a bigram by sliding across 2 words at a time
data = {}
for w in words:
  chars = list(w)
  for ch1, ch2 in zip(chars, chars[2:]):
    bigram = (ch1, ch2)
    data[bigram] = data.get(bigram, 0) + 1



In [3]:
sorted(data.items(), key = lambda kv: -kv[1])

[(('t', 'e'), 11),
 (('a', 'i'), 9),
 (('i', 'g'), 9),
 (('t', 'a'), 7),
 (('i', "'"), 7),
 (('h', 't'), 7),
 (('a', 'e'), 7),
 (('t', 'n'), 7),
 (('y', 'u'), 6),
 (('u', 'e'), 6),
 (('a', 'd'), 6),
 (('e', 'e'), 6),
 (('g', 't'), 5),
 (('I', 'm'), 5),
 (('m', 'n'), 5),
 (('v', 't'), 5),
 (('e', 'l'), 5),
 (('h', 'y'), 5),
 (('v', 'r'), 4),
 (('u', 'i'), 4),
 (('n', 't'), 4),
 (('o', 'e'), 4),
 (('t', 's'), 4),
 (('s', 'r'), 3),
 (('i', 'h'), 3),
 (('t', 't'), 3),
 (("'", 'a'), 3),
 (('r', 'c'), 3),
 (('o', 'i'), 3),
 (('e', 's'), 3),
 (('u', 'm'), 3),
 (('m', 'a'), 3),
 (('m', ','), 3),
 (('a', 's'), 3),
 (('t', 'r'), 3),
 (('r', 'u'), 3),
 (('i', 'e'), 3),
 (('h', 'n'), 3),
 (('e', 'i'), 3),
 (('o', 'f'), 3),
 (('e', 'a'), 3),
 (('l', 'v'), 3),
 (('m', 'k'), 3),
 (('e', 't'), 2),
 (('d', 'o'), 2),
 (('s', 'a'), 2),
 (('t', 'o'), 2),
 (('i', 'n'), 2),
 (('d', 'y'), 2),
 (('a', ','), 2),
 (('i', 's'), 2),
 (('s', 'p'), 2),
 (('p', 'r'), 2),
 (('s', 'm'), 2),
 (('m', '-'), 2),
 (('a', '

In [4]:
chars = sorted(list(set(words)))

In [5]:
import torch

# split the training data

string2integer = {ch: i for i, ch in enumerate(chars)}
print(string2integer)

integer2string = {i:ch for ch,i in string2integer.items()}
encode = lambda s: [string2integer[c] for c in s]
print(encode)

decode = lambda l: ''.join([integer2string[i] for i in l])
print(decode)

data = torch.tensor(encode(words), dtype = torch.long)
print(data)

{'"': 0, '"Hey': 1, '"It\'s': 2, '"Lose': 3, '"Oh,': 4, "'Cause": 5, "'cause": 6, "'em": 7, '(J.J.': 8, 'Doc': 9, 'Fab,': 10, 'Fad)': 11, 'For': 12, 'How': 13, 'I': 14, "I'm": 15, "I'ma": 16, 'Innovative': 17, 'J': 18, 'Lyrics': 19, 'Never': 20, 'Ray': 21, 'So': 22, 'The': 23, 'Throw': 24, 'Uh,': 25, 'Well,': 26, 'What': 27, 'With': 28, 'You': 29, 'Yourself"': 30, 'a': 31, 'and': 32, 'anything': 33, 'are': 34, "assumin'": 35, 'at': 36, 'audience': 37, 'be': 38, 'can': 39, 'celebrating': 40, "comin'": 41, 'confuse': 42, 'day': 43, 'day,': 44, 'demonstrating': 45, 'devastating,': 46, 'do': 47, 'dooma-lumma,': 48, 'elevating': 49, 'elevator': 50, 'ever': 51, 'fading,': 52, 'feeling': 53, 'fell': 54, 'forever': 55, 'found': 56, 'fuse': 57, 'get': 58, 'give': 59, 'glue': 60, 'gotta': 61, 'haters': 62, "he's": 63, 'hella': 64, 'hip-hop,': 65, 'human': 66, 'is': 67, 'it': 68, "it'll": 69, "it's": 70, 'jealous,': 71, 'kill': 72, 'know': 73, 'levitating': 74, 'like': 75, 'lose': 76, 'made': 77,

In [6]:
import torch

n = int(0.4 * len(words))
train_data = data[:n]
val_data = data[n:]
print(val_data)

p = decode(val_data[:18].tolist())
p

tensor([ 32,  15,  46,  81, 107,  51,  45,  13, 114,  59,  31,  82,  37,  31,
         53,  75,  70,  74,  20,  52,  32,  14,  73, 110,  62,  34,  55, 117,
         12, 110,  43, 108, 111,  39,  98,  14,  54,  90, 112,  38,  40,   5,
         14,  73, 110, 118, 114,  58,   7,  83,  14,  79,  49,  85, 123,  79,
         50,  84,   4,  63, 115,  78,  26, 109, 120, 111,  47, 121, 111,  58,
         71, 111,  42,  68,   2,  87,  65,  70,  92,   0,   6,  14,  56,  31,
         64, 118, 114,  57,  68,  28,  96,  99,  94, 122,   9,  24,  91,   3,
         30,  32,  79,   7,  76,  68])


"andI'mdevastating,morethaneverdemonstratingHowtogiveamotherfuckin'audienceafeelinglikeit'slevitating"

In [32]:


ix = torch.randint(len(data) - 5, (12,))
ix

tensor([52,  4, 37, 20, 53, 56,  9, 40, 47,  4, 44, 47])

In [8]:
string2integer = {ch: i for i, ch in enumerate(chars)}
print(string2integer)

res = dict(enumerate(words))
print(res)
keyList = [key for key in res]
print(keyList)
l = len(keyList)
l


{'"': 0, '"Hey': 1, '"It\'s': 2, '"Lose': 3, '"Oh,': 4, "'Cause": 5, "'cause": 6, "'em": 7, '(J.J.': 8, 'Doc': 9, 'Fab,': 10, 'Fad)': 11, 'For': 12, 'How': 13, 'I': 14, "I'm": 15, "I'ma": 16, 'Innovative': 17, 'J': 18, 'Lyrics': 19, 'Never': 20, 'Ray': 21, 'So': 22, 'The': 23, 'Throw': 24, 'Uh,': 25, 'Well,': 26, 'What': 27, 'With': 28, 'You': 29, 'Yourself"': 30, 'a': 31, 'and': 32, 'anything': 33, 'are': 34, "assumin'": 35, 'at': 36, 'audience': 37, 'be': 38, 'can': 39, 'celebrating': 40, "comin'": 41, 'confuse': 42, 'day': 43, 'day,': 44, 'demonstrating': 45, 'devastating,': 46, 'do': 47, 'dooma-lumma,': 48, 'elevating': 49, 'elevator': 50, 'ever': 51, 'fading,': 52, 'feeling': 53, 'fell': 54, 'forever': 55, 'found': 56, 'fuse': 57, 'get': 58, 'give': 59, 'glue': 60, 'gotta': 61, 'haters': 62, "he's": 63, 'hella': 64, 'hip-hop,': 65, 'human': 66, 'is': 67, 'it': 68, "it'll": 69, "it's": 70, 'jealous,': 71, 'kill': 72, 'know': 73, 'levitating': 74, 'like': 75, 'lose': 76, 'made': 77,

172

In [9]:
# scaled dot product attention
# 3 matrices, Q -> query matrix
# K -> Key matrix
# V -> value matrix
# T is the length of the sequence
import math
import numpy as np 
import torch.nn.functional  as F
import torch

def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size()[-1]
    attn_logits = torch.matmul(q, k.transpose(-2, -1))
    attn_logits = attn_logits / math.sqrt(d_k)
    if mask is not None:
        attn_logits = attn_logits.masked_fill(mask == 0, -9e15)
    attention = F.softmax(attn_logits, dim=-1)
    values = torch.matmul(attention, v)
    return values, attention

Dk and Dv
 are the hidden dimensionality for queries/keys and values respectively

In [10]:

import torch
chars = sorted(list(set(words)))
# print(chars)
size = len(chars) # sequence length
# print(size)


d_k = 2

torch.manual_seed(1337)

q = torch.randn(size, d_k)

#q = torch.randn(size, d_k).detach().requires_grad_(True)


k = torch.randn(size, d_k)
v = torch.randn(size, d_k)
values, attention = scaled_dot_product(q, k, v)
# print("Q\n", q)
# print("K\n", k)
# print("V\n", v)
print("Values\n", values[:5].reshape(1, -1))
print("Attention\n", attention[:5].reshape(1, -1))
# p = torch.Tensor(values)
# p

values.tolist()


Values
 tensor([[-0.0024,  0.0350, -0.0502,  0.0396,  0.0462,  0.0850,  0.0854,  0.1279,
          0.0942,  0.0176]])
Attention
 tensor([[0.0082, 0.0072, 0.0058, 0.0073, 0.0079, 0.0100, 0.0100, 0.0078, 0.0066,
         0.0067, 0.0076, 0.0076, 0.0064, 0.0107, 0.0067, 0.0085, 0.0071, 0.0081,
         0.0073, 0.0090, 0.0070, 0.0065, 0.0071, 0.0062, 0.0083, 0.0093, 0.0084,
         0.0106, 0.0094, 0.0092, 0.0097, 0.0066, 0.0079, 0.0071, 0.0103, 0.0086,
         0.0114, 0.0071, 0.0067, 0.0075, 0.0074, 0.0101, 0.0089, 0.0077, 0.0071,
         0.0078, 0.0079, 0.0074, 0.0084, 0.0079, 0.0067, 0.0083, 0.0083, 0.0068,
         0.0084, 0.0078, 0.0060, 0.0077, 0.0079, 0.0081, 0.0072, 0.0071, 0.0091,
         0.0077, 0.0090, 0.0085, 0.0091, 0.0080, 0.0077, 0.0074, 0.0088, 0.0093,
         0.0098, 0.0063, 0.0087, 0.0078, 0.0071, 0.0080, 0.0076, 0.0093, 0.0088,
         0.0073, 0.0080, 0.0063, 0.0082, 0.0078, 0.0072, 0.0103, 0.0080, 0.0086,
         0.0073, 0.0081, 0.0085, 0.0071, 0.0075, 0.0063, 0.00

[[-0.0024424439761787653, 0.034983038902282715],
 [-0.050162434577941895, 0.03959700092673302],
 [0.04617689922451973, 0.0849725529551506],
 [0.08537839353084564, 0.12790806591510773],
 [0.09422025084495544, 0.017580723389983177],
 [-0.1264338195323944, 0.02399449422955513],
 [0.0025612979661673307, 0.04516935721039772],
 [-0.06211200729012489, -0.14241111278533936],
 [0.11488749086856842, 0.18445967137813568],
 [0.051258690655231476, 0.019085988402366638],
 [-0.08051832020282745, -0.1278943568468094],
 [0.20601433515548706, 0.18496564030647278],
 [0.012129737064242363, 0.07835805416107178],
 [-0.10039397329092026, -0.010585248470306396],
 [0.0260832067579031, 0.07921289652585983],
 [1.2068865299224854, -0.21861864626407623],
 [-0.06788432598114014, -0.01689816266298294],
 [0.09440572559833527, 0.13482505083084106],
 [0.047430962324142456, -0.0018940325826406479],
 [-0.09803760796785355, -0.015557516366243362],
 [-0.06463036686182022, 0.039879269897937775],
 [0.04460662603378296, 0.100

In [ ]:
# b = sorted(list(set(values[:n])))

# d  = torch.stack(b)
# d
# g = sorted(list(set(attention[:5])))


###  Tensor ops to be continued

In [ ]:
N = torch.zeros((40, 40), dtype=torch.int32)


### Demystifying queries Keys and Values

In [11]:
words = open('/content/text.txt', 'r').read().split()
words[:20]

['So',
 'Ray',
 'J',
 'went',
 'straight',
 'to',
 'the',
 'radio',
 'station',
 'The',
 'very',
 'next',
 'day,',
 '"Hey',
 'Fab,',
 "I'ma",
 'kill',
 'you!"',
 'Lyrics',
 "comin'"]

In [12]:
import torch
from torch import nn

chars = sorted(list(set(words)))
string2integer = {ch: i for i, ch in enumerate(chars)}
print(string2integer)

integer2string = {i:ch for ch,i in string2integer.items()}
encode = lambda s: [string2integer[c] for c in s]
print(encode)

decode = lambda l: ''.join([integer2string[i] for i in l])
print(decode)

data = torch.tensor(encode(words), dtype = torch.long)
print(data)

{'"': 0, '"Hey': 1, '"It\'s': 2, '"Lose': 3, '"Oh,': 4, "'Cause": 5, "'cause": 6, "'em": 7, '(J.J.': 8, 'Doc': 9, 'Fab,': 10, 'Fad)': 11, 'For': 12, 'How': 13, 'I': 14, "I'm": 15, "I'ma": 16, 'Innovative': 17, 'J': 18, 'Lyrics': 19, 'Never': 20, 'Ray': 21, 'So': 22, 'The': 23, 'Throw': 24, 'Uh,': 25, 'Well,': 26, 'What': 27, 'With': 28, 'You': 29, 'Yourself"': 30, 'a': 31, 'and': 32, 'anything': 33, 'are': 34, "assumin'": 35, 'at': 36, 'audience': 37, 'be': 38, 'can': 39, 'celebrating': 40, "comin'": 41, 'confuse': 42, 'day': 43, 'day,': 44, 'demonstrating': 45, 'devastating,': 46, 'do': 47, 'dooma-lumma,': 48, 'elevating': 49, 'elevator': 50, 'ever': 51, 'fading,': 52, 'feeling': 53, 'fell': 54, 'forever': 55, 'found': 56, 'fuse': 57, 'get': 58, 'give': 59, 'glue': 60, 'gotta': 61, 'haters': 62, "he's": 63, 'hella': 64, 'hip-hop,': 65, 'human': 66, 'is': 67, 'it': 68, "it'll": 69, "it's": 70, 'jealous,': 71, 'kill': 72, 'know': 73, 'levitating': 74, 'like': 75, 'lose': 76, 'made': 77,

In [13]:
vocab_size = len(chars)

d_k = 2

token_emb = nn.Embedding(vocab_size, d_k)
token_emb

Embedding(125, 2)

In [14]:
input_embeddings = token_emb(data)
input_embeddings.size()


torch.Size([172, 2])

#### Now, create the query, key and value vectors and calculate the attention scores based on the dot product as the similarity function

In [15]:
import torch
from math import sqrt 

query = key = value = input_embeddings
dim_k = key.size(-1)
print(dim_k)
scores = torch.matmul(query, key.transpose(1,-2))/sqrt(dim_k)
print(scores)
scores.size()

2
tensor([[ 0.8805,  1.6122,  1.3415,  ...,  0.1712, -0.1440, -1.1985],
        [ 1.6122,  3.6220,  1.5442,  ...,  1.5937, -0.0444, -2.1457],
        [ 1.3415,  1.5442,  3.2844,  ..., -1.4811, -0.5176, -1.8920],
        ...,
        [ 0.1712,  1.5937, -1.4811,  ...,  2.4789,  0.3908, -0.1401],
        [-0.1440, -0.0444, -0.5176,  ...,  0.3908,  0.0952,  0.2119],
        [-1.1985, -2.1457, -1.8920,  ..., -0.1401,  0.2119,  1.6348]],
       grad_fn=<DivBackward0>)


torch.Size([172, 172])

##### Now, lets apply the softmax function

In [16]:
import torch.nn.functional as F
weights = F.softmax(scores, dim = -1)
weights.sum(dim = -1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 

In [17]:
attention_logits = torch.matmul(weights, value)
attention_logits.shape
### Now look at the scaled dot product function above

torch.Size([172, 2])

In [18]:
#m = decode(scores[:3].tolist())
m = scores[:5].tolist()
m[:1]

[[0.880527675151825,
  1.6121827363967896,
  1.3414628505706787,
  -0.6853272914886475,
  -0.5371031165122986,
  -0.07534497231245041,
  -0.4273715317249298,
  -1.0355830192565918,
  0.38905414938926697,
  0.1615649312734604,
  -0.08832787722349167,
  0.454852432012558,
  0.42466068267822266,
  0.7379029989242554,
  1.2833964824676514,
  -0.2417803704738617,
  0.4343053996562958,
  -0.3744153380393982,
  1.0852693319320679,
  1.1492124795913696,
  0.8317149877548218,
  0.5078718066215515,
  0.8317149877548218,
  0.7213720679283142,
  -1.6162853240966797,
  1.2266061305999756,
  0.4563087522983551,
  -1.5484733581542969,
  0.6256605982780457,
  1.0806660652160645,
  0.5078718066215515,
  0.9754514098167419,
  -0.575219452381134,
  -0.04656592011451721,
  -0.46124306321144104,
  0.482714980840683,
  -0.007621599826961756,
  -0.12223619222640991,
  -2.1652355194091797,
  -0.07534497231245041,
  0.18879733979701996,
  -1.1984755992889404,
  0.17231516540050507,
  -0.07534497231245041,
  0.

### Multi headed attention

Having many heads allows the model to focus on different parts of the sentences. The softmax on one head tends to focus on one aspect of similarity. For example subject verb interaction.

### Clean the rest of the Notebook



In [86]:
ix = torch.randint(len(data) - 5, (100,))
ix

tensor([34, 47, 22, 40, 61, 44, 22, 62,  4,  9,  0, 51,  4, 37, 26, 60, 61, 10,
        13, 40, 29,  8, 53, 58, 44, 20, 15, 38, 15, 46,  7, 56,  0, 57, 30, 35,
        51, 22, 53, 31, 28, 53, 10, 55, 26,  3, 39, 33, 48, 27, 31,  0, 48,  4,
        49, 47,  5, 17, 49, 48, 43, 37, 26, 17,  4, 28, 11, 34, 57, 24, 60,  5,
        42, 28, 30, 29, 29, 51, 31, 38, 37,  0, 16, 54, 56, 11, 30, 11, 57, 58,
        10, 55, 55, 40, 54, 13, 37, 27, 45, 42])

In [88]:
x = torch.stack([data[i:i+5] for i in ix])
x

tensor([[ 66,  27,  14,  61,  47],
        [ 17,  32,  15,  77,  88],
        [ 36, 106, 101,   8,  11],
        [ 58,  68, 113, 114, 123],
        [ 88,  80,  32,  69,  60],
        [123,  15, 105,  17,  32],
        [ 36, 106, 101,   8,  11],
        [ 80,  32,  69,  60, 114],
        [103, 114, 110,  93, 102],
        [ 23, 116,  86,  44,   1],
        [ 22,  21,  18, 119, 103],
        [ 88,  97, 100, 108,  33],
        [103, 114, 110,  93, 102],
        [ 61,  47, 114,  58,  68],
        [ 11,  25, 104,  48, 123],
        [ 89,  88,  80,  32,  69],
        [ 88,  80,  32,  69,  60],
        [116,  86,  44,   1,  10],
        [  1,  10,  16,  72, 124],
        [ 58,  68, 113, 114, 123],
        [ 48, 123,  35,  15,  31],
        [102,  23, 116,  86,  44],
        [100, 108,  33,  29,  98],
        [ 67,  95,  89,  88,  80],
        [123,  15, 105,  17,  32],
        [ 36, 123,  36, 106, 101],
        [ 16,  72, 124,  19,  41],
        [ 47, 114,  58,  68, 113],
        [ 16,  72, 1

In [89]:
input_embeddings = token_emb(x)
input_embeddings.size()

torch.Size([100, 5, 2])

In [90]:
## A single attention head

class AttentionHead(nn.Module):
  def __init__(self, embedded_dim, head_dim):
    super().__init__()
    self.q = nn.Linear(embedded_dim, head_dim)
    self.k = nn.Linear(embedded_dim,  head_dim)
    self.v = nn.Linear(embedded_dim,  head_dim)

  def forward(self, x):
    attention_outputs = scaled_dot_product(self.q(x), self.k(x), self.v(x))
    

    return attention_outputs
    


In [91]:
# embedding_dim = embedding dimensions
# num_heads  = number of heads 


class MultiHeadAttention(nn.Module):
  def __init__(self, embedded_dim, num_heads):
    super().__init__()
    self.embedded_dim = embedded_dim
    self.num_heads = num_heads
    head_dim = embedded_dim // num_heads 

    self.heads = nn.ModuleList([AttentionHead(embedded_dim, head_dim) for _ in range(num_heads)])
    self.output_linear = nn.Linear(embedded_dim, embedded_dim)

  def forward(self, x):
    out = torch.cat([h(x) for h in self.heads], dim = -1)
    
    out = self.output_linear(out)

    return out



In [ ]:
multihead_attention = MultiHeadAttention(2,2)
# multihead_attention

output =  multihead_attention(input_embeddings)
output

In [94]:
import torch
chars = sorted(list(set(words)))
# print(chars)
size = len(chars) # sequence length
print(size)

125


In [95]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, input_dim, key_dim, value_dim):
        super(MultiHeadAttention, self).__init__()

        self.num_heads = num_heads
        self.key_dim = key_dim
        self.value_dim = value_dim

        self.query_projection = nn.Linear(input_dim, key_dim * num_heads)
        self.key_projection = nn.Linear(input_dim, key_dim * num_heads)
        self.value_projection = nn.Linear(input_dim, value_dim * num_heads)

        self.output_projection = nn.Linear(value_dim * num_heads, input_dim)

    def forward(self, query, key, value, mask=None):
        batch_size = query.size(0)

        # Project the query, key and value using linear projections
        # and split the resulting tensor into multiple heads
        query = self.query_projection(query).view(batch_size, self.num_heads, self.key_dim)
        key = self.key_projection(key).view(batch_size, self.num_heads, self.key_dim)
        value = self.value_projection(value).view(batch_size, self.num_heads, self.value_dim)

        # Compute the scaled dot-product attention
        # For efficiency, we compute all the dot products in parallel using matrix multiplication
        scores = torch.bmm(query, key.transpose(1, 2)) / (self.key_dim ** 0.5)

        if mask is not None:
            # Mask out the padded positions with a large negative value
            scores = scores.masked_fill(mask == 0, -1e9)

        # Apply the softmax function to get the attention weights
        attention_weights = F.softmax(scores, dim=-1)

        # Apply dropout to the attention weights
        attention_weights = nn.Dropout(p=0.1)(attention_weights)

        # Multiply the attention weights with the value tensor
        context = torch.bmm(attention_weights, value)

        # Concatenate the heads and project the resulting tensor
        context = context.view(batch_size, -1)
        output = self.output_projection(context)

        return output


In [102]:
# Initialize the multi-head attention model with 4 heads, input dimension of 256, key dimension of 64, and value dimension of 64
multi_head_attention = MultiHeadAttention(num_heads=4, input_dim=256, key_dim=64, value_dim=64)

# Create some input tensors
query = torch.randn(size, 256)
key = torch.randn(size, 256)
value = torch.randn(size, 256)

# Apply the multi-head attention
output = multi_head_attention(query, key, value)
output.shape

torch.Size([125, 256])